##############################################################################
# FILENAME: Makefile                                                         #
#                                                                            #
# DESCRIPTION: Makefile for the Vehicle Bluetooth Low Energy Device on the   #
#              vehicle.                                                      #
#                                                                            #
# LICENSE: The MIT License (MIT)                                             #
#          Copyright (c) 2017 Brian Nordland                                 #
#                                                                            #
#  ------------------------------------------------------------------------  #
# | Change  | Date     |            |                                      | #
# | Flag    | (DDMYY)  | Author     | Description                          | #
# |---------|----------|------------|--------------------------------------  #
# | None    | 01Apr17  | BNordland  | Initial creation                     | #
#  ------------------------------------------------------------------------  #
##############################################################################

all: ;

clean: ;